### PR TITLE
Feature/support sunos

### PR DESCRIPTION
**Pull request by dlintw**
Support SunOS

### CODE REVIEW

**Comment by icy** [comment]
Thank you @dlintw  for your work. It's really cool.

I will take a look at this weekend. Stay tuned!

**Comment by icy** [comment]
Hi @dlintw .

I have merged your work, and I slightly changed something . Could you please take a look whether the new script (`make pacapt.dev`) is working on `SunOS`? If that's fine I will merge again on the stable branch (`v2.0`).

Thank you very much.

**Comment by dlintw** [comment]
Yes, it works on SunOS.

**Comment by icy** [comment]
Perfect. Thank you for the double check, @dlintw .

**Pull request merged**
