### PR TITLE
Exherbo Linux support (Paludis package manager)

### PR DESCRIPTION
**Pull request by somasis**

### CODE REVIEW

**Comment by NgoHuy** [comment]
please give me some description what you did, this new distro for us, thank you very much

**Comment by somasis** [comment]
Sorry, I was in a hurry at the time. It just adds support for [Paludis](http://paludis.exherbo.org/), a package manager used in Exherbo Linux. It supports all the operations (except cache-related and package-file ones) that dpkg support does, so far.

**Comment by icy** [comment]
That's awesome, @Somasis :) Thank you for your work!

I will take a look and merge it soon.

**Comment by somasis** [comment]
Alright, thanks :+1:

**Comment by icy** [comment]
hi @Somasis .

I've merged your pull request. Your work is great. Thank you very much.

I've also made some minor changes for your `lib/cave.sh` (add some FIXME entries, fix coding style and some clean up). You may take a look and confirm if that works.

Thanks again,

**Comment by somasis** [comment]
I'll take a look when I get home and see what I can do about your FIXMEs! Thanks for accepting the pull request :)

**Comment by icy** [comment]
@Somasis yes, please :) After you can take a look and  confirm that every `cave` operation is working fine, I can quickly support it in the stable script `pacapt` (as you know, your work is now on the developer one aka `pacapt.dev`.)

Thanks again for your work!

**Comment by icy** [comment]
@Somasis Your work was merged to the stable script .

**Pull request merged**
