### PR TITLE
Use apt search instead of apt-cache when available

### PR DESCRIPTION
**Pull request by VichoReyes**
Because its output is prettier

### CODE REVIEW

**Comment by icy** [comment]
Thanks a lot @esclerofilo . I wil have a look to get around the tests (which uses apt-cache).

**Comment by VichoReyes** [comment]
I hadn't realized apt printed a warning against its use in scripts. It looks like this is a bad idea after all.

**Comment by icy** [comment]
@esclerofilo Why? We don't use all features of the tool. If `apt search` works fine we can go with them.

**Comment by VichoReyes** [comment]
Sorry for the delay
I just think maybe they'll change `apt search` to some other command and pacapt will stop working. If you're fine with fixing it when it happens, then I guess there's no issue.
About the tests, I think the problem is apt prints some messages before showing the search results:
 ```
 
 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
 
 Sorting...
 Full Text Search...
```
While the test expects the output to be empty. We could grep those lines out in the test, but that won't work in different locales. We could also do a `tail -n+2` but it seems cheap and error prone. What do you think?

**Comment by icy** [comment]
hi @esclerofilo , the test can be adjusted quickly (you can also fix that ;). What I'm thinking is to have some configuration (files) for pacapt just in case someone wants to fallback to the non-apt feature.

**Pull request merged**
