### PR TITLE
Make the Homebrew paths more portable and improve the help menu

### PR DESCRIPTION
**Pull request by Arcterus**
This is just in case someone decided to install Homebrew in a non-standard location.

### CODE REVIEW

**Comment by icy** [comment]
Thanks a lot. That's very good. I also see you update the year in the copyright line. Nice catch ;)

Would you mind changing this

```
if [ "$_OSTYPE" = "PACMAN" ]; then
    exec /usr/bin/pacman "$@"
fi
```

into this

```
if [[ "$_OSTYPE" == "PACMAN" ]]; then
    exec /usr/bin/pacman "$@"
fi
```

They are almost the same, except that we use the builtin (`[[`), not the external command (`[`).

**Comment by Arcterus** [comment]
Done. :)

**Comment by icy** [comment]
Thank you! And sorry that I miss another one

```
 if [ -e \${files[\${#files[@]} - 1]} ]; then 
```

Basically we won't use `[` . Please fix and I merge pull request then.

Thanks a lot.

**Comment by icy** [comment]
Thank you @Arcterus . I've merged the pull. It's perfect :)

**Pull request merged**
