### PR TITLE
yum groupinfo and yum grouplist support

### PR DESCRIPTION
**Pull request by NgoHuy**
- Thêm hỗ trợ cho lệnh `yum grouplist` và lệnh `yum groupinfo packages`.

### CODE REVIEW

**Comment by icy** [comment]
@NgoHuy The 'pacapt' script should be generated with a "good" version. In the past, it was "2.0.0-gamma". Would you mind selecting a better name instead of using a git hash (which is unreadable)? You may use "2.0.0-delta" (See [1] and [2])

Note: you don't need to delete this pull request. You only need to create new commit on the branch.

[1] https://en.wikipedia.org/wiki/Greek_alphabet
[2] https://github.com/icy/pacapt/blob/ng/Makefile#L12

**Comment by icy** [comment]
Btw, can you take at look if we can support the group feature on various operating systems?

**Comment by xiongchiamiov** [comment]
I'm fairly certain homebrew doesn't have the concept of meta-groups, so that one's a simple not-implemented error.

**Comment by NgoHuy** [comment]
@xiongchiamiov ya, I found that `dpkg` doesn't support meta-packages search too. But any distro supports meta-packages search, we should support them.

**Comment by icy** [comment]
I close this pull request because

1/ It casues conflict
2/ The file 'pacapt' is generated. This script is in stable status and it should not be generated as mentioned in `CONTRIBUTING` file.

**Pull request closed without merging**
