### PR TITLE
Use which to detect OS type

### PR DESCRIPTION
**Pull request by 10sr**
Command brew should not be used while detecting OS type. This emits error like 'command not found' in systems where brew is not installed.

### CODE REVIEW

**Comment by icy** [comment]
Thank you. I will take a look.

**Comment by Arcterus** [comment]
Maybe this should use `command -v PROGNAME >/dev/null` instead of `which PROGNAME >/dev/null`?  That way it will be using a bash builtin.

**Comment by 10sr** [comment]
I see. I updated to use `command`. Should I send another pull request that has only one commit for this change?

**Comment by icy** [comment]
> That is true. I updated to use `command`.

`command` is better than `which`. However, see below.

> Should I send another pull
> request that has only one commit for this change?

It's possible to use the current branch to provide more commits.

Now back to the original problem. This pull request does exist because we are trying to solve the problem with `brew`, which may have different prefixes (depends on the installation). 

Except for `brew`, all other package managers are not involved: On standard system, `apt-get` should be found at `/usr/bin/apt-get`; `pacman` should be found at `/usr/local/bin/pacman`. By using `command`, `which`, we assume `apt-get` would be found in some different on the systems, and **any of them may be possible**.

**Comment by icy** [comment]
The side effect is that, if on Debian-based system I install `pacapt` as `/usr/local/bin/pacman` (due to history reason, there are a lot of installation that uses the name `pacman`, not `pacapt` as in the latest documentation), the first test 

`command -v pacman >/dev/null && _OSTYPE="PACMAN"`

would yield **Debian is an ArchLinux system** -- that's not correct. When we enlarge the set of destinations where we want to locate the package manager, we have more possibilities to solve. That's not really thing we want. I suggest that we still keep the old tests, and only solve the problem for `brew` where we can use the test `command -v brew`. Please let me know if there is any problem.

**Comment by icy** [comment]
Please note that if `pacapt` is installed as `/usr/bin/pacman` we would have a similar problem. But that's another thing we need to fixed.

**Comment by 10sr** [comment]
I updated!

**Comment by icy** [comment]
Thank you very much, @10sr

**Pull request merged**
