### PR TITLE
Add FreeBSD's pkgng support.

### PR DESCRIPTION
**Pull request by sugar700**
I decided to create a support for FreeBSD, just because [pkgng](https://wiki.freebsd.org/pkgng) is great. Requires `bash` package to be installed (it isn't by default in FreeBSD). The reason why `/usr/bin/env bash` is used is that FreeBSD uses `/usr/local/bin/bash`.

### CODE REVIEW

**Comment by icy** [comment]
Thank you very much @GlitchMr . FreeBSD cool:) it's great to have `pkgng` support in `pacapt`

 I'm working on this pull request. I will keep you posted.

**Comment by icy** [comment]
Hi @GlitchMr ,

Here are some comments would you mind taking a look?
1. The documentation would be updated in the script, not directly in README.md file. This is because README.md is generated (to help Github). Please check the function `_help()`.
2. The function `_exec_` was updated to support `install` for FreeBSD's `pkg`. However, this only happens once for the `S`ynchornization operation. I think it's better to add a trick (e.g, on the line 687) instead of changing the function `_exec_` that would alter on all distributions. This is because I really want to use `$@` expansion feature, not `$*` feature (that may be a different in any future use.)
3. Is there any better way to detect if FreeBSD is being used? It's good to use `/usr/sbin/pkg`; it just wonder if there is more robust way.

Thanks again for your work.

**Comment by sugar700** [comment]
`uname -a | grep -q FreeBSD` could work, but I'm not sure about running unrelated programs. There is no `/etc/issue`.

**Comment by NgoHuy** [comment]
@xfix , Do you have `/etc/os-release` ? I saw that we can replace `/etc/issue` with `/etc/*-release`

**Comment by icy** [comment]
On May 4th, 2014, the `master` branch is closed. The script is written in a new way, and can be found on the `ng` branch. This pull request will not be merged. However, I keep it open, because we will find a way to integrate the function into the `ng` branch (by creating new library file `lib/pkgng.sh`)

**Comment by icy** [comment]
Feature implemented in
- https://github.com/icy/pacapt/commit/0ac4acc0c3ebbc1d02f1e048ba76c484c0e79103 (main library)
- https://github.com/icy/pacapt/commit/3e000ad746f330a4e9eb52b784d4f242eaf2cf83 (compiler support)
- https://github.com/icy/pacapt/commit/4c2c3924e18fcf8c0f4004e24ed83323fc7de71a (readme)
- https://github.com/icy/pacapt/commit/72a632260490846dd121fc2a9ee881aa0cd7ee11 (argument parsing)
- https://github.com/icy/pacapt/commit/fef4d5870b371dc7aa04140e0707db7ea2a5f3e7 (shebang fix)

**Pull request closed without merging**
