### PR TITLE
OpenBSD pkg_tools support

### PR DESCRIPTION
**Pull request by somasis**
This adds support for `pkg_add`, `pkg_delete`, `pkg_info`, etc on OpenBSD, collectively known as `pkg_tools`.

In addition, I solved a bug found while trying to use it on OpenBSD, which is the shebang used on the scripts. Using `#!/bin/bash` on OpenBSD (and confirmed on FreeBSD, actually) doesn't work, because it's installed to /usr/local/bin/bash; so, `#!/usr/bin/env bash` is used instead, which should be compatible with just about any common *nix system.

I've tested it on my OpenBSD server, so it should be fine.

### CODE REVIEW

**Comment by icy** [comment]
Awesome, @Somasis :) Thank you very much for your work. 

I'm going to take a look and merge your work soon.

**Comment by somasis** [comment]
Alright, thank you :)

**Comment by icy** [comment]
@Somasis Your work has been merged. There's some minor problem that I will fix soon. Thanks again for your work!

**Comment by somasis** [comment]
I just fixed a bug with -Q having no query given, it should handle it properly now. If you tell me what the problem you found is, I'll investigate it as well.

**Comment by icy** [comment]
Of course, @Somasis .

As you can see here [1](line 97) the removal may happen after a failed `cd` or an unwanted `cd`. For example, if you set up the variable `PKG_CACHE` for some other program, and you forget it when you invoke `pacapt`, you may accidently remove all files under `/`. 

The question is whether there a way to make sure that `PKG_CACHE` is the right directory, or not. And is that a fixed directory so that we don't need to rely on `PKG_CACHE` variable?

[1] https://github.com/Somasis/pacapt/commit/9756ed47059ebc7854f19d18351d8e8595431e9a#diff-99f6602fb8e6bf1c75daf8162780d93dR97

**Comment by icy** [comment]
Btw, I don't really know exactly how the similar problem is solved in other package manager. I will take a look.

**Comment by somasis** [comment]
By default there isn't a cache used, we have to trust what the user sets `$PKG_CACHE` to. So, there's not really a fixed directory to rely on.

I just commited a test for the directory, though. If `$PKG_CACHE` is empty, it will say that you need to set it. If `$PKG_CACHE` is not empty, but the directory does not exist, it will say that it does not exist. If it does exist, and `$PKG_CACHE` isn't empty, it'll clean the cache.

Concerning making sure the directory specified is the right one though, I don't believe there's a right way to do so. All that can really be done is making sure it exists.

**Comment by somasis** [comment]
Also, I've made some new commits to the repository so if you'd pull my changes it should fix a few of the problems, including better `$PKG_CACHE` checking

**Comment by icy** [comment]
@Somasis Thanks again. Your work and fixes have been merged onto the `ng` branch.

**Comment by icy** [comment]
> I just commited a test for the directory, though. If $PKG_CACHE is empty, it will say that you need to set it. > If $PKG_CACHE is not empty, but the directory does not exist, it will say that it does not exist. If it does > exist, and $PKG_CACHE isn't empty, it'll clean the cache.

Where is the commit? I don't see it . The current code is still

```
    cd "$PKG_CACHE"
    if [[ "$_TOPT" != "--noconfirm" ]];then
      # don't blindly delete everything in a directory!
      rm -irf *
    else
      # unless they really want to...
      rm -rf *
    fi
```

I also suggest to use a strict constraint here. For example,

```
    cd "$PKG_CACHE" && {
      # do something
    }
```

This is to make sure that the we won't delete wrong files when the `cd` command failed on a correct folder.

**Comment by somasis** [comment]
It is on my fork (https://github.com/Somasis/pacapt), it includes some bug fixes to pkg_tools, as well as the Makefile so that it works with non-GNU `make`.

**Comment by somasis** [comment]
Sorry, I thought I pushed it but apparently not.

**Comment by xiongchiamiov** [comment]
FYI, if you invoke bash with the `-e` option (or use `set -e`/`set +e`), bash will abort on an non-zero exit code it encounters*.  I've found that to be extremely helpful in writing bash scripts, and in reducing manual error-checking.

---

\* There are some subtleties.  In particular, `set -o pipefail` is required if you want to exit when a command in a pipechain fails, and failing commands inside test conditions (`[`, `[[`) don't exit the script.

**Comment by icy** [comment]
Sorry for the noise in the deleted messages. My mouse was broken.

@Somasis: Thanks for the update. I merged your request #35 .

**Comment by somasis** [comment]
No problem, thanks for accepting it

**Comment by icy** [comment]
@xiongchiamiov You're right. When using `set -e` all errors should be handled carefully. It's not easy but it's worth considering the feature in the future.

**Pull request merged**
