### PR TITLE
Void Linux Support

### PR DESCRIPTION
**Pull request by TabulateJarl8**
I was bored so I added support for Void Linux. Not sure if I did anything wrong, but I'm pretty sure I've checked all of the contributing boxes and all of the tests pass. Hope this is helpful!

### CODE REVIEW

**Comment by icy** [comment]
> I was bored so I added support for Void Linux. Not sure if I did anything wrong, but I'm pretty sure I've checked all of the contributing boxes and all of the tests pass. Hope this is helpful!

Hi @TabulateJarl8 ,

thanks for your contribution. The old PR has some conflicts and your new one is cleaner. I will have a look today and add some tests so that it can be merged quickly.

Best,

**Comment by icy** [comment]
Hi @TabulateJarl8 ,

I don't think you've enabled GithubActions on your forked repository so I need to check out and run some tests locally. Congratulaions: It's all fine now! I've merged the PR and will include them in the next release very soon.

Thanks again for your contribution.

**Comment by TabulateJarl8** [comment]
Sorry for the inconvenience, and you're very welcome for the contribution!

**Comment by TabulateJarl8** [comment]
One thing I did notice, I seem to have forgotten to add it to the README, unless that's automatically generated, and also there's still some issues for void support open. Just figured I'd give you a heads up.

**Comment by icy** [comment]
> Sorry for the inconvenience, and you're very welcome for the contribution!

No worries, it's also very easy to run tests locally and I often do that ;)

> One thing I did notice, I seem to have forgotten to add it to the README, unless that's automatically generated, and also there's still some issues for void support open. Just figured I'd give you a heads up.

The table of all operations is updated with `make update_stats` ( and I did, they're on the `ng` branch now). I can help to update (mention) the support in the new release, no worries. You then can focus on the fix ;)

**Pull request merged**
