### PR TITLE
Implement -Sw for apt

### PR DESCRIPTION
**Pull request by pabru**
I noticed that APT supports an equivalent command, so I've added -Sw support for APT. I'm not sure if the syntax conforms to the coding style, could someone please check?

### CODE REVIEW

**Comment by icy** [comment]
Hi @pabru,

Thanks for your contribution. 

The option `-w` is translated to correct option for `apt`, as you can see in https://github.com/icy/pacapt/blob/ng/lib/00_core.sh#L119 . The table doesn't record this translation and that's why the option `Sw` is missed from the table in `README` file.

Your PR is still useful. I will merge it and provide some information in the source.

Thanks again and I'm sorry for any confusion.

**Comment by pabru** [comment]
Sorry about that, I had a very brief look at the 00_core.sh when looking for the right place to implement this option, but I didn't notice the part with _translate_w. I hope my contribution is still useful. :)
Coincidentally, which place is the right one to put the -w option?

**Comment by icy** [comment]
@pabru,

Ideally, you would write `dpkg_Sw`, `dpkg_Suw`,... and so on. Here `-w` isn't an operation, it's an `option` which can be used by different actions. That's why there is a common method `_translate_w`. That's quite inconsistent, but it works so far.

Update: Fix typo error.

**Comment by pabru** [comment]
OK, thanks a lot for clarifying.

**Comment by icy** [comment]
You're welcome, @pabru .

**Pull request merged**
