### PR TITLE
Add Gentoo

### PR DESCRIPTION
**Pull request by cmpitg**
Hi Ky Anh,

I have added support for Gentoo, refactored the code a bit, and fixed some typo.  Would you like to take my changes?

Dương

### CODE REVIEW

**Comment by icy** [comment]
Thank you very much, Dương. Gentoo support is awesome :)

I will take a look at your changes and give feedback soon.

Regards,

**Comment by cmpitg** [comment]
My pleasure, Kỳ Anh :-). I'm looking forward to your comments.

Kindest regards,
Dương

**Comment by kyanh** [comment]
Hi Duong,

Your pull request was merged. I made some small changes to clean up. Please check my commits for details.

Thank you again for the patches. That's so awesome :)

Regards,

**Comment by cmpitg** [comment]
Hi Kỳ Anh,

Not at all.  Thank you :-).  It looks great!

Best regards,
Dương

**Pull request merged**
