### PR TITLE
Add all remove methods for zypper

### PR DESCRIPTION
**Pull request by dasJ**
What the title says: -Rs, -Rns

### CODE REVIEW

**Comment by icy** [comment]
Hi @dasJ ,

Thanks for your work. I need to review this pull carefully, because of the "removing" feature. There is also some conflict now. 

I will keep you posted.

**Comment by dasJ** [comment]
Just fixed the conflicts :)

**Comment by icy** [comment]
Thanks a lot :)

**Comment by dasJ** [comment]
Fixed it again

**Comment by icy** [comment]
Hi @dasJ,

Thanks for your update.

The reason this PR is delayed, is that I'm thinking of a way to secure the "removal" feature. As you know, remove anything from the filesystem is quite risk [1]; the actual problem is that we use data from other program, and we have no way to make sure data are safe.

There are different solutions: (1) Just print what the script would remove, and ask users to confirm; (2) Harden our script by some strict checks. E.g, before executing `rm -rf $file`, we need to ensure `$file` is actual a file and belongs to the package.

Any ideas?

[1] https://github.com/icy/bash-coding-style#good-lessons

**Comment by dasJ** [comment]
I thought it was sure enough that it is a file and belongs to the package. Or is there any other way to test one of these?

**Comment by icy** [comment]
See also 
- https://github.com/icy/pacapt/commit/fea21e6838735089630718d0c208e20dd6761c47
- https://github.com/icy/pacapt/commit/ece4df8f959d94c98451c94e6aa8de3b2ba0ca03

I've updated the code to use a `while` loop to remove the configuration files, then remove the packages. The force (`-f`) option was dropped, too.

**Comment by splashx** [comment]
@icy if `-f` was dropped, how to pacapt on Ubuntu non-interactive? 

UPDATE: use `-- -y`

**Pull request merged**
