### PR TITLE
pkg_tools: add support for -Sl, clean up -Sy/Su a little

### PR DESCRIPTION
**Pull request by somasis**

### CODE REVIEW

**Comment by somasis** [comment]
@icy Also, would you mind giving me push ability? I'd like to continue adding support/improving some support for the stuff I've added + other package managers, but I'd rather not keep having to make pull requests for it. If you don't want to give it to me, that's fine though.

**Comment by icy** [comment]
@Somasis Thank you very much for your request. I understand that's because you want to contribute your best to the project.

I will think twice about this, because I need to make sure that they feel fair. I will keep you posted!

Thanks for your understanding.

**Comment by somasis** [comment]
Alright, thanks

**Comment by icy** [comment]
@Somasis Hi again. I'm sorry for my belated response. I have to jump back and forth between projects :)

Currently, the `pacact` repository can be updated directly by two people: me, and @NgoHuy. Huy is a member of my local team. However, in his last pull request he is updating the stable script `pacapt` directly, which is not a good way. I don't really like this , so I haven't merged  his work yet. (Fortunately, he agreed that he would not push directly to the repository even though he can always do it.)

The key is that we need to keep the 'pacapt' script (it's generated) as stable as possible (as you know, we have two different verions of the script. See README for details.) Our `pacapt` is now widely used, and as developers we are happy to see that. But that also requires us to work hard. Because a bad script will make system _(where 'pacapt' is installed)_ dangerous.

I am happy to provide you more privileges, so you can work on the development script quickly. But I need to ensure that the main script is calm. After a period (6 months or 1 year, or when we are ready), we will cherry pick and/or merge the features from 'dev' script on to the 'stable' one.

Actually, I am bit busy, and I really like to see someone can take over the work. Providing you and other contributors write permissions is fine. But the first thing is to make sure we are on the same board, same way :)

Let me know what you think. I also like to hear from @xiongchiamiov @dupuy and other contributors. They really make the project live!

Thanks a lot.

**Comment by somasis** [comment]
Thanks for responding, and don't worry about it being late, you're fine.

You're saying that once the development branch becomes the main branch, then I would be given write privileges? If so, that's just fine. I'd be glad to become a main developer on the project, thanks for the response and information.

**Comment by xiongchiamiov** [comment]
Adding more trusted people is nice because it helps prevent bottlenecks when you're busy with other things (as you are).

I've found that for projects that have a few team members, I like to still open pull requests, even if I can just commit directly, because that allows someone else to check me with code review - which helps find the silly mistakes I tend to make often.  At reddit, we use [a bot](https://github.com/spladug/harold) combined with [some emoji](https://github.com/reddit/reddit/wiki/The-Beauty-Salon) to do this, but it can be as simple as just opening a pull and waiting for someone to :+1: it.

**Pull request merged**
